### PR TITLE
Make normalizeVariableHeader work

### PR DESCRIPTION
**Pull request by jshin313**
This fixes Issue #21 and fixes inconsistencies with other types of variables (Pictures and YVars).

### CODE REVIEW

**Comment by KermMartian** [comment]
@jshin313 awesome, thank you! Did you perform any regression testing using the included examples?

**Comment by jshin313** [comment]
I tested the HelloWorld.ino on both TI-84+ and TI-84+ CSE

**Comment by Eric02851** [comment]
Please merge this if you get the chance @KermMartian.

**Comment by KermMartian** [comment]
Thanks, @Eric02851 @jshin313 !

**Comment by Eric02851** [comment]
Thanks :)

**Pull request merged**
